enableGlobalCache: false
enableTelemetry: false
nodeLinker: node-modules

cacheFolder: ../../.yarn/cache
# this file comes from berry--yarnpkg-cli-4.4.0.zip!/berry--yarnpkg-cli-4.4.0/packages/yarnpkg-cli/bin/yarn.js
# berry--yarnpkg-cli-4.4.0.zip comes from https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/4.4.0.zip
# which can be found at https://github.com/yarnpkg/berry/releases
# (please add "-<version>" qualifier)
yarnPath: ../../.yarn/releases/yarn-4.4.0.js
